### ISSUE TITLE
As simple standard CSV-reader what is better?

### ISSUE THREAD

**Issue by ppKrauss** [evanplaice/jquery-csv#137]
(question) About *"... a more modern take on CSV parsing ..."* at the [README](https://github.com/typeiii/jquery-csv/blob/master/README.md).

This project is from 2013, and for use as plug-in with jQuery, in "Javascript for browser" context (not NodeJs). But you recommended [CSV-ES](https://github.com/vanillaes/csv-es)...  By other hand you are working hard recent years, [updating the project in 2019 and 2020](https://github.com/typeiii/jquery-csv/graphs/contributors?from=2019-01-13&to=2020-01-05&type=c)...

So, can you explain when I must use CSV-ES and when (context/conditions) jquery-csv?

**Comment by evanplaice** [comment]
I'm glad you asked

In short, CSV-ES is a re-implementation of the algorithm used in jquery-csv. It's built using all the lessons I learned from maintaining this project over the years.

It's smaller...
I cut out most of the less commonly used features (ex configurable delimiters). That reduced the size from ~1k LOC to about 1/5th the size.

It has a more intuitive API...
Instead of inventing a new API, CSV-ES mimics JSON by providing just `parse()` and `stringify()` functions.

It's faster...
The jquery-csv parser algo is already really fast. CSV-ES is tuned even more.

It's modern...
CSV-ES doesn't rely on old non-standard module formats. Jquery-CSV targets IIFE/AMD/UMD. CSV-ES ships ESM and CJS<sup>1</sup> module. ESM works seamlessly in both browsers and the latest Node. 

*<sup>1</sup> CommonJS is provided to use w/ Node/bundlers until ESM support officially lands in the Node LTS.*

It's tree shakeable...
If you bundle CSV-ES, unused code won't appear in the output.

It's typed...
Typescript typings (ie *.d.ts) are provided so it 'just works' with Typescript. Also, if you use VSCode then Intellisense and inline documentation will work as well.

-----

About the hard work on jquery-csv. That was just regular maintenance. I wanted to close out most/all existing issues and update the process/tooling to follow my current best workflows.

It takes a lot of effort to maintain a project over a multi-year time frame. Closing everything out and updating the processes ensure it takes very little effort -- on my part -- to keep this project going.

There's nothing wrong with using jquery-csv if you're already using jquery.

If you are no longer targeting Internet Explorer, working with the latest frameworks/bundlers, or building on the latest standards (ie ESM, Web Components) then CSV-ES should be a lot easier to work with.

Also, in the long-term I plan to officially deprecate this lib when it hits the 10 year mark (ie 2022/4/20).
