### ISSUE TITLE
Flot graph - Pointing to url of CSV file on Server and access data

### ISSUE THREAD

**Issue by uidev369** [evanplaice/jquery-csv#55]
I am trying to get data from a csv file on the server so pointing a url of that csv file. I see in the demo that we can select files from file system.. Is there a way we can point a url of csv file on server and get the data

**Comment by evanplaice** [comment]
This library follows 'The Prinicple of Least Astonishment'. Basically, it takes a CSV string as input and outputs structured data.

The online example just leverages the HTML5 File API to load the CSV string from a local file. To fetch the CSV data from a remote source you just make a AJAX GET request to a url and pass the string data received into the parser.

I'm reluctant to add an example that fetches data from a user-provided URL because of the potential for abuse (ie XSS).
