### ISSUE TITLE
not on bower.io

### ISSUE THREAD

**Issue by bnomei** [evanplaice/jquery-csv#56]
can not find this repo on bower. it should be there?
http://bower.io/search/?q=jquery-csv

**Comment by evanplaice** [comment]
Awesome, thanks for the heads up.

Another dev had previously posted an outdated fork of the lib to bower and I was unable to post updated versions. I'll get this added again within the next few days.

**Comment by evanplaice** [comment]
It's there but it was initially registered by another dev hosting an unofficial dirty fork of the project.

I don't have an issue with forks but the dev responsible for the fork has since disappeared. Requests to update Bower with the latest have gone unanswered. Due to the first-come-first-serve basis of Bower registrations I'm unable to replace it with the latest from this repo.

I submitted an issue reference above. We'll see what the Bower devs have to say about it. Hopefully, this issue can be corrected so I can finally update the Bower registry with the latest version of jquery-csv.

Thank you for your input :+1:

**Comment by evanplaice** [comment]
@bnomei Here's an update

I filed an issue on the Bower repo. A bower dev is giving the other dev who registered his fork on Bower under jquery-csv a week to reply and stop the registration from being changed. Even if he does respond, I highly doubt he'd block the switch.

As soon as I have access to register the project I'll update the package to the latest.

**Comment by bnomei** [comment]
cool :+1:

**Comment by evanplaice** [comment]
@bnomei This should be resolved now

**Comment by BFrancoeur** [comment]
Thanks, Evan:)

**Comment by bnomei** [comment]
thx.
