### ISSUE TITLE
fails to process json encoded  string fields 

### ISSUE THREAD

**Issue by mmikrut** [evanplaice/jquery-csv#63]
exported from mysql, below csv line fails to load at column 20,

"1","email","me@facebook.com","etstde1","Active",,"14.56888040","121.02260110","Ciline Gonzalo","63","9876543210","F","29","1","5","","La Maison Rada Condominium, street, city,country","14.55592096","121.01839540","[\"home\",\"inhouse\"]",NULL,NULL,"0.2","400","400","400","400","400","400","400","3500",,

**Comment by evanplaice** [comment]
That's because your CSV output is invalid. GIGO applies.

According to the spec, escaping a double-quote is done with another double-quote `""` not a backslash `\"`.

The following value is invalid:
``"[\"home\",\"inhouse\"]"``

A valid output would be:
`"[""home"",""inhouse""]"`

*Source: Rule #7 of [IETF RFC 4180](https://tools.ietf.org/html/rfc4180)*

The rest is very mixed/inconsistent but valid and should parse without issue.
