### ISSUE TITLE
bug fix in $.csv.fromArrays()

### ISSUE THREAD

**Issue by wujun** [evanplaice/jquery-csv#70]
at lines 853 in jquery.csv.js file . It looks like to be modified:
 strValue = strValue.replace(new RegExp(config.delimiter, 'g' ), config.delimiter + config.delimiter); 
insead of strValue = strValue.replace(config.delimiter, config.delimiter + config.delimiter); which
means replace all single delimiter with double ones I think.

**Comment by evanplaice** [comment]
OK. Had do double-check this just to ensure my assumptions were correct.

```javascript
strValue.replace(new RegExp(config.delimiter, 'g'), config.delimiter + config.delimiter);
```

Assume `strValue` represents an entry. Since an entry may contain more than one double-double delimiter value, this line needs to match all instances of the delimiter to match them.

An more clear representation of the RegEx is.

```javascript
replace(\delimiter\g, `${delimiter}${delimiter}`)
```

What you're suggesting is

```javascript
replace(\delimiter\, `${delimiter}${delimiter}`)
```

Which only matches the first instance of a delimiter.

So, the sample input:

```javascript
[
    ["All work","and no play","makes Jack","a \"dull\" boy..."],
]
```

Would incorrectly output as

```
All work,and no play,makes Jack,"a ""dull" boy..."
```


 The ugly `new RegEx` is just an alternative to the typical backslashed RegEx syntax except it's necessary here because the value being used is variable. In short, dynamic Regexes suck.

**Comment by evanplaice** [comment]
I added some tests in a461b81cd49b50ddf220ba3ee3c9d689815d669e to check/demonstrate the usage.
