### ISSUE TITLE
Javascript?

### ISSUE THREAD

**Issue by suriyaJaay** [evanplaice/jquery-csv#71]
hi,

can you pls update this with javascript version which is capable of running on nodejs.?

am working on but failed in every attempt 

thank you
Happy New Year

**Comment by tytskyi** [comment]
Really, what is the reason of keeping it coupled to jQuery? 
As far as i understand it does not use jQuery internally.

**Comment by evanplaice** [comment]
@tytskyi There is no reason to justifiable reason to keep this project coupled with jquery. I am and have been aware of that fact for a very long time now.

I'd like to convert the codebase over to ES6+, for readability as well as better module import namespace support. Unfortunately, this change would require dropping jquery-csv altogether. My initial intent was to extend the jquery pseudo-monad so this could be used in a typical jquery chain but the more I learned about jquery, the more I realized that would be a bad idea.

One major reason this project became so popular to begin with was the name. Choosing names is difficult, and one major limitation of NPM is that once a name is reserved, it's not trivial to transfer to another project.

I'm aware of a project named [javascript-csv](https://github.com/mageddo/javascript-csv) that hosts an outdated fork of this project. If I can convince the dev of that project to transfer the name over, that'll be a great place to start transitioning to the new model.

That has been on the back of my mind, but I'd really prefer to wait until native ES6+ support is available in all browsers before I make any major changes. I've mostly left things as they are up until now because major API breaking changes are very time consuming to implement, test, and support.

The time and resources I have to devote to this project have been very limited. If that changes in the near/distant future, you'll start to see progress start up again.

----

I'd like to hit the goals in 0.9 first before any major structural changes are made to the project. To assist in making this a reality I've just posted the [Roadmap for 0.9](#92), and posted jquery-csv on CodeTriage.
