### ISSUE TITLE
How generate a Google graph from a date time csv file

### ISSUE THREAD

**Issue by lcoulon** [evanplaice/jquery-csv#73]
Hello,

I'm totally newbie and need to generate a google graph from date time stamps in X axis and Temperature value in Y axis, something like this : https://jsfiddle.net/99guxm3b/4

I need the values to be parsed from a CSV file, this file with be automotically filled-in with datas every x minutes.

How should i format my CSV or TXT file to let that file readable in order to generate the lines accordlingly in the Google Graph function drawChart() ?

 data.addRows([
          [new Date(Year, Month, Day, Hours, Minutes, Seconds, Milliseconds), YaxisValue]
 ]);

 or 
 data.addRows([
          [new Date(Milliseconds), YaxisValue]
 ]);

Once CSV file properly defined , what function should i use to parse datas and generate the graph ?

If someone could show me the way to proceed from a jsfiddle.net example, i could help me a lot.
Regards,

**Comment by arashsoft** [comment]
You should report issues here not questions. Please use Stackoverflow to ask questions.

**Comment by evanplaice** [comment]
This lib doesn't deal directly with Google Visualization other than providing a simple demo. With that said, the parser has some more advanced capabilities that can be leveraged to properly prepare your input data.

If you were to use CSV you could store the values in the [new Date(Milliseconds), YaxisValue] format. Do parse toArrays() and input the resulting 2D array into the data.addRows.

To get the data from a file into a 2D array check out the [Google Visualization Demo](http://evanplaice.github.io/jquery-csv/examples/google-visualization.html) specifically lines 142-152.

Since the parser treats all data as text you'll need to add another step to cast the values to the correct types. That's where hooks become useful, specifically the onParseValue hook. The lib already includes a generic hook definition used to detect and cast scalar values:

 *$.csv.hooks.castToScalar*

    castToScalar: function(value, state) {
        var hasDot = /\./;
        if (isNaN(value)) {
          return value;
        } else {
          if (hasDot.test(value)) {
            return parseFloat(value);
          } else {
            var integer = parseInt(value);
            if(isNaN(integer)) {
              return null;
            } else {
              return integer;
            }
          }
        }
    }

Use this as a template to create your own custom hook.

Since you already know the structure of the data you can erase the body of the hook that deals with type detection. Just make sure the function signature `hook(value, state)` is maintained. The `state` property is used to track the current row/col, and the `value` is the value currently being parsed -- this is what you'll need to cast and return.

Here are the properties of the `state` object.

    state: {
      rowNum: 1,
      colNum: 1
    }

So, to properly convert your data add conditionals for `if(rowNum === 1)` and `if(rowNum === 2)`. When you're done defining the callback hook assign it to the `onParseValue` property of the parser definition as seen in lines 142-152 of the demo.

When the parser spits out a 2D array it should contain the data cast to the correct types. Simply, use it at the data source for your graph and it should just work.
