### ISSUE TITLE
\ in csv will return as \\

### ISSUE THREAD

**Issue by Cameron1122** [evanplaice/jquery-csv#84]
using a csv file of:
test1,test2
data1,data2\3

will result in
[
 {
  "test1":"data1",
  "test2":"data2\\3"
 }
]

**Comment by freethewhat** [comment]
What would be the expected result of this? Should it remove the \ or catch an error?

**Comment by evanplaice** [comment]
Not sure if it's a markdown quirk but in your original comment the result looks identical to your data.

It shouldn't attempt to escape backslashes. If the result outputs a double backslash, then the bug is confirmed.

The lexer uses regex to separate terminals/non-terminals. The data itself may contain chars that have special meaning in regex so the parser has to properly escape these. If the bug is confirmed, then I'm pretty backslash isn't a special char in regex so escaping it is a mistake.

**Comment by freethewhat** [comment]
So I ran toArrays and to objects on: 

test1,test2
data1,data2\3

and was returned an array of arrays with:

```
[
  ["test1", "test2"],
  ["data1", "data2\3]
[

{
  test1: "test2",
  data1: "data2\3"
}
```

Looks like this might be a non-issue.

**Comment by evanplaice** [comment]
Is the output JSON. If so, backslashes *should* be escaped or the data would be invalid.

**Comment by evanplaice** [comment]
OK, the original output is correct. To display a value containing a backslash it should show the backslash being escaped by a second backslash.

If there was just one backslash it would interpret the `\3` as unicode `\u0003`. 

To see this in action, open your Chrome dev console and paste

```javascript
console.log([{test1: 'data', test2: 'data2\3'}]);
```

Then try

```javascript
console.log([{test1: 'data', test2: 'data2\\3'}]);
```

The first will try to place an invalid unicode char. The second should display the correct value. For some reason node shows both. I'm going to mark this bug as invalid for now, if it's still causing any issues feel free to comment and I'll reopen.
